#
# Docker image for production
#

FROM node:14-alpine
RUN apk update && apk add --no-cache libc6-compat nano

# ld-linux-x86-64 is required by uWebsocket
RUN ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2
