#
# Docker image for building and testing microservices
#

FROM ghcr.io/waytrade/microservice-core/microservice-prodution:latest

# install JDK
RUN apk add openjdk11

# install OpenAPI tools
RUN npm install --global @openapitools/openapi-generator-cli
RUN openapi-generator-cli version
